export const ACTIONS = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SORT_BY_HIGH_TO_LOW: "SORT_BY_HIGH_TO_LOW",
  SORT_BY_LOW_TO_HIGH: "SORT_BY_LOW_TO_HIGH",
  SORT_BY_BRAND: "SORT_BY_BRAND",
  SORT_BY_SIZES: "SORT_BY_SIZES",
  SORT_BY_IDEAL_FOR: "SORT_BY_IDEAL_FOR",
  CLEAR_FILTER: "CLEAR_FILTER",
};
